pimcore_js_translations:
    path: /translations.{format}
    controller: Instride\Bundle\PimcoreJsTranslationBundle\Controller\TranslationController::getTranslationsAction
    defaults: { format: 'js' }
    methods: [GET]
    options:
        i18n: false
        expose: true
    requirements:
        format: js|json
