pimcore_js_translations:
    path:  /translations.{format}
    defaults: { _controller: Wvision\Bundle\PimcoreJsTranslationBundle\Controller\TranslationController::getTranslationsAction, format: 'js' }
    methods: [GET]
    options:
        i18n: false
        expose: true
    requirements:
        format: js|json
