services:

    # Pimcore Website Translation Event Subscriber
    Wvision\Bundle\PimcoreJsTranslationBundle\EventSubscriber\PimcoreWebsiteTranslationEventSubscriber:
        arguments:
            - '@Wvision\Bundle\PimcoreJsTranslationBundle\Filesystem\TranslationFileGenerator'
        tags:
            - { name: kernel.event_subscriber }
