services:

    # Xliff Translation Loader
    Wvision\Bundle\PimcoreJsTranslationBundle\Loader\XliffTranslationLoader:
        arguments:
            - '%pimcore_js_translation.domain_name%'
            - '@translation.loader.xliff'
